### ISSUE TITLE
template/template_V2.txt is missing 

### ISSUE THREAD

**Issue by askerdb** [nthomasCUBE/BioSankey#1]
It seems like the file template/template_V2.txt is missing from the repository.

When running the use cases:

python 0_make_html.py expr=Use_case_1/GENES.txt deg=Use_case_1/DEG_information dom=Use_case_1/DOMAINS.txt > Use_case_1.html
Traceback (most recent call last):
  File "0_make_html.py", line 7, in <module>
    fh=file("template/template_V2.txt")
IOError: [Errno 2] No such file or directory: 'template/template_V2.txt

**Comment by nthomasCUBE** [comment]
Hi askerdb,

file has been added

best regards+many thanks,
thomas
